### ISSUE TITLE
Error: Invalid log level.  Using the default instead.

### ISSUE THREAD

**Issue by OliverwengFiltered** [logdna/logdna-winston#34]
```
 Error: Invalid log level.  Using the default instead.
17:53:04 1|web                | 2021-09-20T17:53:04:     at Logger.log (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/@logdna/logger/lib/logger.js:575:21)
17:53:04 1|web                | 2021-09-20T17:53:04:     at LogDNATransport.log (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/logdna-winston/index.js:44:17)
17:53:04 1|web                | 2021-09-20T17:53:04:     at LogDNATransport._write (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston-transport/index.js:82:19)
17:53:04 1|web                | 2021-09-20T17:53:04:     at doWrite (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/readable-stream/lib/_stream_writable.js:428:64)
17:53:04 1|web                | 2021-09-20T17:53:04:     at writeOrBuffer (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/readable-stream/lib/_stream_writable.js:417:5)
17:53:04 1|web                | 2021-09-20T17:53:04:     at LogDNATransport.Writable.write (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/readable-stream/lib/_stream_writable.js:334:11)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.ondata (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:681:20)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.emit (events.js:376:20)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.emit (domain.js:470:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at addChunk (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:298:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at readableAddChunk (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:280:11)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Readable.push (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:241:10)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Transform.push (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:139:32)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger._transform (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/lib/winston/logger.js:305:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Transform._read (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Transform._write (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83)
17:53:04 1|web                | 2021-09-20T17:53:04:     at doWrite (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:409:139)
17:53:04 1|web                | 2021-09-20T17:53:04:     at writeOrBuffer (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:398:5)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Writable.write (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:307:11)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.ondata (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:681:20)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.emit (events.js:376:20)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.emit (domain.js:470:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at addChunk (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:298:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at readableAddChunk (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:280:11)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Readable.push (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:241:10)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Transform.push (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:139:32)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger._transform (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/lib/winston/logger.js:305:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Transform._read (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Transform._write (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83)
17:53:04 1|web                | 2021-09-20T17:53:04:     at doWrite (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:409:139)
17:53:04 1|web                | 2021-09-20T17:53:04:     at writeOrBuffer (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:398:5)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.Writable.write (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:307:11)
17:53:04 1|web                | 2021-09-20T17:53:04:     at DerivedLogger.log (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/winston/lib/winston/logger.js:210:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at ServerResponse.res.end (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/api-service/FilteredSharedFiles/node_modules/express-winston/index.js:425:41)
17:53:04 1|web                | 2021-09-20T17:53:04:     at Gzip.onStreamEnd (/Users/oliverweng/Desktop/DevelopmentApps/Filtered/node_modules/compression/index.js:212:14)
17:53:04 1|web                | 2021-09-20T17:53:04:     at Gzip.emit (events.js:376:20)
17:53:04 1|web                | 2021-09-20T17:53:04:     at Gzip.emit (domain.js:470:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at endReadableNT (internal/streams/readable.js:1336:12)
17:53:04 1|web                | 2021-09-20T17:53:04:     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
17:53:04 1|web                | 2021-09-20T17:53:04:   meta: {
17:53:04 1|web                | 2021-09-20T17:53:04:     got: '\x1B[32MINFO\x1B[39M',
17:53:04 1|web                | 2021-09-20T17:53:04:     expected: [ 'TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL' ],
17:53:04 1|web                | 2021-09-20T17:53:04:     used: 'INFO'
17:53:04 1|web                | 2021-09-20T17:53:04:   }
17:53:04 1|web                | 2021-09-20T17:53:04: }
```

started getting the above error when upgrading the logdna-winston to the latest version.

This is our initialization snippet looks like
![Screen Shot 2021-09-20 at 5 56 42 PM](https://user-images.githubusercontent.com/28814939/134081292-434cebb5-f708-4811-9c96-0d5b7e831f28.png)

wondering is anyone has any insights on how to solve the issue after upgrading.

**Comment by OliverwengFiltered** [comment]
I think when using this logdna-winston package with express-winston, you can always reproduce the issue. 

so the problem may be the express-winston package ?

**Comment by OliverwengFiltered** [comment]
looks like it's the ` colorize` option in express-winston is messing it up, it's all set now. thanks.
