### ISSUE TITLE
A connection based error occurred

### ISSUE THREAD

**Issue by rashadksh** [logdna/logdna-winston#39]
**Version**: 3.0.5
**Winston version**: 3.2.1
**Error log**:
```
Error: A connection-based error occurred that will not be retried. See meta data for details. 
  at /app/backend/node_modules/logdna/logger/lib/logger.js:867:29
  at processTicksAndRejections (internal/process/task_queues.js:77:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
```

> Couldn't find a way to reproduce, it randomly happened and crashed the server

**Comment by jsumners** [comment]
We are unable to assist without a reproduction.
